version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-and-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Setup Node.js 20
          command: |
            nvm install 20
            nvm use 20
      - run:
          name: Build project
          command: npm run build
          environment:
            CI: false # Bỏ qua các cảnh báo ESLint, tương tự GitHub Actions
      - run:
          name: Deploy to Azure Static Web Apps
          command: |
            npm install -g @azure/static-web-apps-cli
            swa deploy ./build --api-token $AZURE_STATIC_WEB_APPS_API_TOKEN
          environment:
            AZURE_STATIC_WEB_APPS_API_TOKEN: $AZURE_STATIC_WEB_APPS_API_TOKEN

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - circleci-project-setup # Tương ứng với branch trong GitHub Actions
