version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Create artifacts directory
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: cp -R build ~/artifacts
      - store_artifacts:
          path: ~/artifacts
          destination: node-build
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Deploy to GitHub Pages
          command: |
            npm install -g gh-pages
            gh-pages -d build
          environment:
            GITHUB_TOKEN: $GITHUB_TOKEN
workflows:
  build-and-deploy:
    jobs:
      - build-node
      - deploy:
          requires:
            - build-node
          filters:
            branches:
              only:
                - circleci-project-setup