version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-and-deploy:
    executor:
      name: node/default
      tag: "20.12.2"
    steps:
      - checkout
      - run:
          name: Install dependencies and update lockfile
          command: npm install
      - run:
          name: Clean install dependencies
          command: npm ci
      - run:
          name: Build project
          command: npm run build
          environment:
            CI: false # Đảm bảo bỏ qua cảnh báo ESLint
      - run:
          name: Deploy to Azure Static Web Apps
          command: |
            npm install -g @azure/static-web-apps-cli
            swa deploy ./build --api-token $AZURE_STATIC_WEB_APPS_API_TOKEN
          environment:
            AZURE_STATIC_WEB_APPS_API_TOKEN: $AZURE_STATIC_WEB_APPS_API_TOKEN

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - circleci-project-setup
